CREATE ROLE postgres WITH LOGIN PASSWORD <PASSWORD>;
GRANT ALL PRIVILEGES ON DATABASE postgres to postgres;
REVOKE ALL PRIVILEGES ON DATABASE postgres FROM PUBLIC;
REVOKE ALL PRIVILEGES ON DATABASE root FROM PUBLIC;
GRANT ALL PRIVILEGES ON DATABASE root TO root;
